---
server:
    port: 8888
spring:
    cloud:
        config:
            server:
                git:
                    uri:https://github.com/nstarev/spring-cloudconfig-wa-tolls
                    #username: custom_username
                    #password: pass